[build]
  command = "npm run build" # adjust the build command as needed
  publish = "/client/build" # adjust the path to the build output
  functions = "/client/functions" # if you have serverless functions

[[redirects]]
  from = "/*"
  to = "/client/:splat"
  status = 200
  force = true
